from itertools import combinations, chain

from lenscalc import Lens

# Create iterables for parametrized tests
single_variables = combinations(Lens.variables, 1)
pairs = combinations(Lens.variables, 2)
triplets = combinations(Lens.variables, 3)
combinations_of_4 = combinations(Lens.variables, 4)
combinations_of_5 = combinations(Lens.variables, 5)
combinations_of_6 = combinations(Lens.variables, 6)

combinations_failing = [
    ('nL', 'r1', 'r2', 'CT'),
    ('D1', 'nL', 'r1', 'r2', 'CT'),
    ('D1', 'nL', 'r2', 'P1', 'FFL'),
    ('D2', 'nL', 'r1', 'r2', 'CT'),
    ('D2', 'nL', 'r1', 'P2', 'BFL'),
    ('D', 'n1', 'nL', 'n2', 'EFL'),
    ('D', 'nL', 'r1', 'r2', 'CT'),
    ('n1', 'nL', 'r1', 'r2', 'CT'),
    ('nL', 'n2', 'r1', 'r2', 'CT'),
    ('nL', 'r1', 'r2', 'CT', 'P1'),
    ('nL', 'r1', 'r2', 'CT', 'P2'),
    ('nL', 'r1', 'r2', 'CT', 'f1'),
    ('nL', 'r1', 'r2', 'CT', 'f2'),
    ('nL', 'r1', 'r2', 'CT', 'EFL'),
    ('nL', 'r1', 'r2', 'CT', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'NPS'),
    ('D1', 'D2', 'nL', 'P1', 'FFL'),
    ('D1', 'D2', 'nL', 'P2', 'BFL'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'BFL'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'NPS'),
    ('D1', 'D2', 'n1', 'nL', 'P1', 'FFL'),
    ('D', 'nL', 'n2', 'r1', 'r2', 'CT'),
    ('D1', 'D2', 'nL', 'P1', 'P2', 'FFL'),
    ('D1', 'D2', 'nL', 'P1', 'P2', 'BFL'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'P1'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'P2'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'f1'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'f2'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'EFL'),
    ('D', 'nL', 'r1', 'r2', 'CT', 'FFL'),
    ('D1', 'D2', 'n1', 'nL', 'P2', 'BFL'),
    ('D1', 'D2', 'nL', 'P1', 'f1', 'FFL'),
    ('D1', 'D2', 'nL', 'P1', 'f2', 'FFL'),
    ('D1', 'D2', 'nL', 'P1', 'EFL', 'FFL'),
    ('n1', 'nL', 'n2', 'r1', 'r2', 'CT'),
    ('D1', 'D2', 'nL', 'P1', 'FFL', 'BFL'),
    ('D1', 'D2', 'nL', 'P1', 'FFL', 'NPS'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'P1'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'P2'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'f1'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'f2'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'EFL'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'FFL'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'BFL'),
    ('n1', 'nL', 'r1', 'r2', 'CT', 'NPS'),
    ('D1', 'D2', 'nL', 'P2', 'f1', 'BFL'),
    ('D1', 'D2', 'nL', 'P2', 'f2', 'BFL'),
    ('D1', 'D2', 'nL', 'P2', 'EFL', 'BFL'),
    ('D1', 'D2', 'nL', 'P2', 'FFL', 'BFL'),
    ('D1', 'D2', 'nL', 'P2', 'BFL', 'NPS'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'P1'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'P2'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'f1'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'f2'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'EFL'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'FFL'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'BFL'),
    ('nL', 'n2', 'r1', 'r2', 'CT', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'P2'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'f1'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'f2'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'EFL'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'P1', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'f1'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'f2'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'EFL'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'P2', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'f1', 'f2'),
    ('nL', 'r1', 'r2', 'CT', 'f1', 'EFL'),
    ('nL', 'r1', 'r2', 'CT', 'f1', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'f1', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'f1', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'f2', 'EFL'),
    ('nL', 'r1', 'r2', 'CT', 'f2', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'f2', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'f2', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'EFL', 'FFL'),
    ('nL', 'r1', 'r2', 'CT', 'EFL', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'EFL', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'FFL', 'BFL'),
    ('nL', 'r1', 'r2', 'CT', 'FFL', 'NPS'),
    ('nL', 'r1', 'r2', 'CT', 'BFL', 'NPS'),
    ('D1', 'n1', 'nL', 'r1', 'r2', 'CT'),
    ('D1', 'D2', 'nL', 'n2', 'P1', 'FFL'),
    ('D1', 'D', 'nL', 'r1', 'r2', 'CT'),
    ('D1', 'n1', 'nL', 'r2', 'P1', 'FFL'),
    ('D1', 'D', 'nL', 'r2', 'P1', 'FFL'),
    ('D1', 'D2', 'nL', 'n2', 'P2', 'BFL'),
    ('D1', 'n1', 'CT', 'P1', 'f1', 'NPS'),
    ('D1', 'n1', 'CT', 'f1', 'FFL', 'NPS'),
    ('D1', 'nL', 'r2', 'P1', 'P2', 'FFL'),
    ('D1', 'nL', 'r2', 'P1', 'f1', 'FFL'),
    ('D1', 'nL', 'r2', 'P1', 'f2', 'FFL'),
    ('D1', 'nL', 'r2', 'P1', 'EFL', 'FFL'),
    ('D1', 'nL', 'r2', 'P1', 'FFL', 'BFL'),
    ('D1', 'nL', 'r2', 'P1', 'FFL', 'NPS'),
    ('D1', 'nL', 'n2', 'r1', 'r2', 'CT'),
    ('D1', 'nL', 'n2', 'r2', 'P1', 'FFL'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'P1'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'P2'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'f1'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'f2'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'EFL'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'FFL'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'BFL'),
    ('D1', 'nL', 'r1', 'r2', 'CT', 'NPS'),
    ('D1', 'D2', 'D', 'nL', 'P1', 'FFL'),
    ('D2', 'D', 'nL', 'r1', 'r2', 'CT'),
    ('D2', 'D', 'nL', 'r1', 'P2', 'BFL'),
    ('D1', 'D2', 'D', 'nL', 'P2', 'BFL'),
    ('D2', 'n1', 'nL', 'r1', 'P2', 'BFL'),
    ('D2', 'n1', 'nL', 'r1', 'r2', 'CT'),
    ('D2', 'nL', 'n2', 'r1', 'r2', 'CT'),
    ('D2', 'nL', 'r1', 'P1', 'P2', 'BFL'),
    ('D2', 'nL', 'n2', 'r1', 'P2', 'BFL'),
    ('D2', 'nL', 'r1', 'P2', 'f1', 'BFL'),
    ('D2', 'nL', 'r1', 'P2', 'f2', 'BFL'),
    ('D2', 'nL', 'r1', 'P2', 'EFL', 'BFL'),
    ('D2', 'nL', 'r1', 'P2', 'FFL', 'BFL'),
    ('D2', 'nL', 'r1', 'P2', 'BFL', 'NPS'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'P1'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'P2'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'f1'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'f2'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'EFL'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'FFL'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'BFL'),
    ('D2', 'nL', 'r1', 'r2', 'CT', 'NPS'),
    ('D2', 'n2', 'CT', 'P2', 'f2', 'NPS'),
    ('D2', 'n2', 'CT', 'f2', 'BFL', 'NPS'),
    ('D', 'n1', 'nL', 'n2', 'P1', 'EFL'),
    ('D', 'n1', 'nL', 'n2', 'P2', 'EFL'),
    ('D', 'n1', 'nL', 'n2', 'f1', 'EFL'),
    ('D', 'n1', 'nL', 'n2', 'f2', 'EFL'),
    ('D', 'n1', 'nL', 'n2', 'EFL', 'FFL'),
    ('D', 'n1', 'nL', 'n2', 'EFL', 'BFL'),
    ('D', 'n1', 'nL', 'n2', 'EFL', 'NPS'),
    ('D', 'n1', 'nL', 'r1', 'r2', 'CT'),
]

combinations_of_4_passing = [c for c in combinations_of_4 if c not in combinations_failing]
combinations_of_5_passing = [c for c in combinations_of_5 if c not in combinations_failing]
combinations_of_6_passing = [c for c in combinations_of_6 if c not in combinations_failing]

combinations_passing = chain(
    single_variables,
    pairs,
    triplets,
    combinations_of_4_passing,
    combinations_of_5_passing,
    combinations_of_6_passing,
)
